
services:
  frontend:
    build: .
    ports:
      - "8080:8080" # or 8080:8080 if you're using Vue CLI
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run serve
